/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cai_jnitest_JniMethod */

#ifndef _Included_com_cai_jnitest_JniMethod
#define _Included_com_cai_jnitest_JniMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cai_jnitest_JniMethod
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cai_jnitest_JniMethod_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_cai_jnitest_JniMethod
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cai_jnitest_JniMethod_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_cai_jnitest_JniMethod
 * Method:    acceessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_cai_jnitest_JniMethod_acceessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_cai_jnitest_JniMethod
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cai_jnitest_JniMethod_chineseChars
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
